# Generated by Django 3.0 on 2019-12-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('amount', models.IntegerField(db_index=True)),
                ('currency', models.CharField(max_length=50)),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashcog.Employee')),
            ],
        ),
    ]
