# Generated by Django 3.0 on 2020-01-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashcog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee_uuid',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
